apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: canary-pipeline
spec:
  params:
  - name: tag
    description: Tag to use for newly built image
  resources:
  - name: source-repo
    type: git
  - name: image
    type: image
  - name: cluster
    type: cluster
  tasks:
  - name: build-image
    taskRef:
      name: kaniko-tag
    params:
    - name: TAG
      value: ${params.tag}
    resources:
      inputs:
      - name: source
        resource: source-repo
      outputs:
      - name: image
        resource: image
  - name: create-canary
    taskRef:
      name: canary-deployment
    params:
    - name: pathToDeployment
      value: "config/200-deployment.yaml"
    - name: pathToHPA
      value: "config/300-hpa.yaml"
    - name: pathToVirtualService
      value: "config/600-virtualservice.yaml"
    - name: pathToDestinationRule
      value: "config/700-destinationrule.yaml"
    - name: tag
      value: ${params.tag}
    resources:
      inputs:
      - name: source
        resource: source-repo
      - name: cluster
        resource: cluster
      - name: image
        resource: image
        from: [build-image]
  - name: scale-canary-90
    runAfter: [create-canary]
    taskRef:
      name: scale
    params:
    - name: baselinePercent
      value: "90"
    - name: canaryPercent
      value: "10"
    - name: pathToVirtualService
      value: "config/600-virtualservice.yaml"
    resources:
      inputs:
      - name: source
        resource: source-repo
      - name: cluster
        resource: cluster
  - name: scale-canary-75
    runAfter: [scale-canary-90]
    taskRef:
      name: scale
    params:
    - name: baselinePercent
      value: "75"
    - name: canaryPercent
      value: "25"
    - name: pathToVirtualService
      value: "config/600-virtualservice.yaml"
    resources:
      inputs:
      - name: source
        resource: source-repo
      - name: cluster
        resource: cluster
  - name: scale-canary-50
    runAfter: [scale-canary-70]
    taskRef:
      name: scale
    params:
    - name: baselinePercent
      value: "50"
    - name: canaryPercent
      value: "50"
    - name: pathToVirtualService
      value: "config/600-virtualservice.yaml"
    resources:
      inputs:
      - name: source
        resource: source-repo
      - name: cluster
        resource: cluster