apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: canary-pipeline
spec:
  params:
  - name: tag
    description: Tag to use for newly built image
  resources:
  - name: source-repo
    type: git
  - name: image
    type: image
  tasks:
  - name: build-image
    taskRef:
      name: kaniko-tag
    params:
    - name: TAG
      value: ${params.tag}
    resources:
      inputs:
      - name: source
        resource: source-repo
      outputs:
      - name: image
        resource: image
