apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cats
  namespace: catspace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cats
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 99
